ParoleNet:
  dropout_p: 0.1
  hidden_dim: 32
  input_dim: 91392
  output_dim: 2
evaluate:
  turn_after: 0.184756
get_audio:
  duration: 2
get_text:
  context_length: 20
  pad_token: <pad>
name: ParoleNet_0.2
sampling:
  seed: 2002
  test_fraction: 0.05
  val_fraction: 0.05
training:
  batch_size: 96
  nb_epochs: 20
  scheduler:
    gamma: 0.1
    initial_lr: 0.001
    step_size: 5
