name : ParoleNet_2

get_audio:
  duration: 2

get_text:
  context_length: 20
  pad_token: "<pad>"

training:
  batch_size: 64
  nb_epochs: 10
  scheduler:
    initial_lr: 0.01
    step_size: 5
    gamma: 0.1

ParoleNet:
  input_dim: None
  hidden_dim_1_layer: 128
  hidden_dim_2_layer: 32
  output_dim: 2
  dropout_p: 0.1

evaluate: 
  turn_after: 0.184756

sampling: 
  seed: 42
  test_fraction: 0.1
  val_fraction: 0.1

