ParoleNet:
  dropout_p: 0.05
  hidden_dim_1_layer: 128
  hidden_dim_2_layer: 32
  input_dim: None
  output_dim: 2
evaluate:
  turn_after: 0.184756
get_audio:
  duration: 2
get_text:
  context_length: 20
  pad_token: <pad>
name: ParoleNet_0.3
sampling:
  seed: 2002
  test_fraction: 0.1
  val_fraction: 0.1
training:
  batch_size: 128
  nb_epochs: 20
  scheduler:
    gamma: 0.1
    initial_lr: 0.001
    step_size: 5
